import type {
  AuditEntry,
  Evidence,
  Followup,
  Interaction,
  Patient,
  Project,
  SafetyLead,
  Signal,
} from './types'

export const demoProjects: Project[] = [
  {
    id: '00000000-0000-4000-8003-000000000001',
    name: 'CardioPress Post-Market Safety Watch',
    status: 'active',
    project_type: 'post_market_surveillance',
    countries: ['ES', 'DE'],
    languages: ['es', 'de', 'en'],
    channels_enabled: ['phone', 'app', 'whatsapp', 'caregiver_app'],
    sla_hours: 72,
    patient_count: 248,
    lead_count: 58,
    brand_name: 'CardioPress',
  },
]

export const demoLeads: SafetyLead[] = [
  {
    id: 'lead-1',
    lead_number: 'SL-01001',
    status: 'urgent_review',
    urgency: 'urgent',
    is_serious: false,
    seriousness_criteria: ['near_fall', 'confusion_needs_review'],
    event_description: 'Dizziness + missed dose; near-fall risk',
    suggested_meddra_pt: 'Dizziness',
    suggested_meddra_code: '10013573',
    suspected_product: 'CardioPress 10 mg',
    dose: '10 mg oral daily',
    outcome: 'Unknown',
    completeness_score: 82,
    missing_fields: ['exact_onset_date', 'outcome', 'medical_attention', 'concomitant_medications'],
    ai_narrative:
      'P-ES-042 reported dizziness after starting CardioPress 10 mg and skipped one dose because she was afraid she would fall. A caregiver reported confusion and an almost-fall in the bathroom. Follow-up is required for onset, outcome, medical attention, and concomitant medicines. Human PV review required before sponsor handoff.',
    ai_confidence: 92,
    primary_channel: 'phone',
    received_at: '2025-06-27T09:42:00Z',
    sla_due_at: '2025-06-27T13:42:00Z',
    patient_ref: 'P-ES-042',
    age_group: 'late 70s',
    sex: 'F',
    country: 'ES',
    assigned_to_name: 'Dr. R. Moreno',
  },
  {
    id: 'lead-2',
    lead_number: 'SL-01002',
    status: 'in_medical_review',
    urgency: 'urgent',
    is_serious: true,
    seriousness_criteria: ['medically_important'],
    event_description: 'Extreme fatigue with dyspnoea and lower-limb heaviness',
    suggested_meddra_pt: 'Dyspnoea',
    suggested_meddra_code: '10013968',
    suspected_product: 'CardioPress (Lisinopril)',
    dose: '20mg oral daily',
    outcome: 'Unknown',
    completeness_score: 58,
    missing_fields: ['concomitant_medications', 'outcome_confirmed', 'medical_assessment'],
    ai_narrative:
      'P-3421 reported extreme fatigue, breathing difficulty, and heavy legs by phone. Concomitant medicines and outcome are not yet confirmed. Medical review is in progress. Human PV review required.',
    ai_confidence: 86,
    primary_channel: 'phone',
    received_at: '2026-06-27T04:30:00Z',
    sla_due_at: '2026-06-28T04:30:00Z',
    patient_ref: 'P-3421',
    age_group: '76-80',
    sex: 'M',
    country: 'ES',
    assigned_to_name: 'Dr. R. Moreno',
  },
  {
    id: 'lead-3',
    lead_number: 'SL-01003',
    status: 'needs_followup',
    urgency: 'standard',
    is_serious: false,
    seriousness_criteria: [],
    event_description: 'Myalgia with two missed doses this week',
    suggested_meddra_pt: 'Myalgia',
    suggested_meddra_code: '10028411',
    suspected_product: 'CardioPress (Lisinopril)',
    dose: '5mg oral daily',
    outcome: 'Unknown',
    completeness_score: 44,
    missing_fields: ['onset_date', 'dose_timing', 'outcome', 'reason_for_missed_doses'],
    ai_narrative:
      'P-8891 reported persistent limb pain via WhatsApp and disclosed two missed doses. The report includes a possible adverse event and a medication error. Onset date and outcome are unknown. Human PV review required.',
    ai_confidence: 87,
    primary_channel: 'whatsapp',
    received_at: '2026-06-27T06:30:00Z',
    sla_due_at: '2026-06-29T02:30:00Z',
    patient_ref: 'P-8891',
    age_group: '71-75',
    sex: 'M',
    country: 'DE',
  },
  {
    id: 'lead-4',
    lead_number: 'SL-01004',
    status: 'ai_structured',
    urgency: 'standard',
    is_serious: false,
    seriousness_criteria: [],
    event_description: 'Persistent dry cough since starting medication',
    suggested_meddra_pt: 'Cough',
    suggested_meddra_code: '10011224',
    suspected_product: 'CardioPress (Lisinopril)',
    dose: '10mg oral daily',
    outcome: 'Ongoing',
    completeness_score: 61,
    missing_fields: ['onset_date', 'duration', 'prior_history_of_cough'],
    ai_narrative:
      'P-1145 reported a persistent dry cough via app after starting CardioPress. Onset date and prior history are missing. Human PV review required before any seriousness decision.',
    ai_confidence: 96,
    primary_channel: 'app',
    received_at: '2026-06-26T22:30:00Z',
    sla_due_at: '2026-06-29T10:30:00Z',
    patient_ref: 'P-1145',
    age_group: '65-70',
    sex: 'F',
    country: 'DE',
  },
]

export const demoEvidence: Evidence[] = [
  {
    id: 'ev-1',
    lead_id: 'lead-1',
    evidence_type: 'primary_interaction',
    channel: 'phone',
    reporter_type: 'patient',
    transcript_text:
      'New pill made me dizzy. I skipped it yesterday because I was afraid I would fall.',
    observation_type: 'adverse_event_and_missed_dose',
    verbatim_extract: 'new pill made me dizzy; skipped it yesterday; afraid I would fall',
    suggested_meddra_pt: 'Dizziness',
    ai_confidence: 92,
    interaction_at: '2025-06-27T09:42:00Z',
  },
  {
    id: 'ev-2',
    lead_id: 'lead-1',
    evidence_type: 'caregiver_confirmation',
    channel: 'caregiver_app',
    reporter_type: 'caregiver',
    transcript_text: 'She seemed confused this week and almost fell in the bathroom.',
    observation_type: 'fall_risk',
    verbatim_extract: 'confused this week and almost fell in the bathroom',
    suggested_meddra_pt: 'Fall',
    ai_confidence: 88,
    interaction_at: '2025-06-27T10:05:00Z',
  },
  {
    id: 'ev-3',
    lead_id: 'lead-3',
    evidence_type: 'primary_interaction',
    channel: 'whatsapp',
    reporter_type: 'patient',
    transcript_text:
      'My legs and arms ache all the time. Also I skipped two doses this week because I forgot.',
    observation_type: 'medication_error',
    verbatim_extract: 'skipped two doses this week because I forgot',
    suggested_meddra_pt: 'Medication error',
    ai_confidence: 95,
    interaction_at: '2026-06-27T06:30:00Z',
  },
]

export const demoSignals: Signal[] = [
  {
    id: 'sig-1',
    drug: 'CardioPress',
    reaction_meddra_pt: 'Angioedema',
    reaction_meddra_code: '10002424',
    n: 47,
    prr: 4.21,
    ror: 4.53,
    ebgm: 3.91,
    chi_squared: 38.2,
    signal_status: 'review',
    last_computed_at: '2026-06-27T09:00:00Z',
    notes: 'Disproportionate against pilot background rates; serious labeled event.',
  },
  {
    id: 'sig-2',
    drug: 'CardioPress',
    reaction_meddra_pt: 'Dyspnoea',
    reaction_meddra_code: '10013968',
    n: 23,
    prr: 2.41,
    ror: 2.46,
    ebgm: 2.18,
    chi_squared: 12.1,
    signal_status: 'monitor',
    last_computed_at: '2026-06-27T09:00:00Z',
  },
  {
    id: 'sig-3',
    drug: 'CardioPress',
    reaction_meddra_pt: 'Cough',
    reaction_meddra_code: '10011224',
    n: 156,
    prr: 1.89,
    ror: 1.91,
    ebgm: 1.76,
    chi_squared: 7.2,
    signal_status: 'monitor',
    last_computed_at: '2026-06-27T09:00:00Z',
  },
  {
    id: 'sig-4',
    drug: 'CardioPress',
    reaction_meddra_pt: 'Peripheral oedema',
    reaction_meddra_code: '10034835',
    n: 41,
    prr: 1.54,
    ror: 1.55,
    ebgm: 1.49,
    chi_squared: 3.8,
    signal_status: 'baseline',
    last_computed_at: '2026-06-27T09:00:00Z',
  },
]

export const demoInteractions: Interaction[] = [
  {
    id: 'int-1',
    patient_ref: 'P-7234',
    reporter_type: 'patient',
    channel: 'app',
    transcript_text:
      'My face keeps swelling up and it is hard to swallow since I started the new blood pressure pill.',
    language: 'en',
    ai_processed: true,
    safety_mention_detected: true,
    observations_count: 2,
    interaction_at: '2026-06-27T08:20:00Z',
  },
  {
    id: 'int-2',
    patient_ref: 'P-3421',
    reporter_type: 'patient',
    channel: 'phone',
    transcript_text: 'I have extreme tiredness and trouble breathing, my legs feel very heavy.',
    language: 'es',
    ai_processed: true,
    safety_mention_detected: true,
    observations_count: 1,
    interaction_at: '2026-06-27T04:30:00Z',
  },
  {
    id: 'int-3',
    patient_ref: 'P-8891',
    reporter_type: 'patient',
    channel: 'whatsapp',
    transcript_text:
      'My legs and arms ache all the time. Also I skipped two doses this week because I forgot.',
    language: 'de',
    ai_processed: true,
    safety_mention_detected: true,
    observations_count: 2,
    interaction_at: '2026-06-27T06:30:00Z',
  },
]

export const demoFollowups: Followup[] = [
  {
    id: 'fu-1',
    lead_id: 'lead-3',
    lead_number: 'SL-01003',
    patient_ref: 'P-8891',
    task_type: 'question_to_patient',
    question_text:
      'When did the muscle pain start? Was it before or after you began the blood pressure medicine?',
    channel: 'whatsapp',
    status: 'pending',
    due_at: '2026-06-28T06:30:00Z',
  },
  {
    id: 'fu-2',
    lead_id: 'lead-1',
    lead_number: 'SL-01001',
    patient_ref: 'P-7234',
    task_type: 'question_to_caregiver',
    question_text:
      'Can you confirm whether emergency care was sought for the swelling or swallowing difficulty?',
    channel: 'caregiver_app',
    status: 'sent',
    due_at: '2026-06-27T17:00:00Z',
  },
]

export const demoPatients: Patient[] = [
  {
    id: 'pat-1',
    patient_ref: 'P-7234',
    age_group: '71-75',
    sex: 'F',
    country: 'ES',
    language: 'es',
    condition: 'Hypertension',
    preferred_channel: 'app',
    consent_status: 'consented',
    status: 'active',
    lead_count: 1,
    interaction_count: 2,
  },
  {
    id: 'pat-2',
    patient_ref: 'P-3421',
    age_group: '76-80',
    sex: 'M',
    country: 'ES',
    language: 'es',
    condition: 'Hypertension, Heart failure',
    preferred_channel: 'phone',
    consent_status: 'consented',
    status: 'active',
    lead_count: 1,
    interaction_count: 1,
  },
  {
    id: 'pat-3',
    patient_ref: 'P-8891',
    age_group: '71-75',
    sex: 'M',
    country: 'DE',
    language: 'de',
    condition: 'Hypertension',
    preferred_channel: 'whatsapp',
    consent_status: 'consented',
    status: 'active',
    lead_count: 1,
    interaction_count: 1,
  },
]

export const demoAudit: AuditEntry[] = [
  {
    id: 'audit-1',
    created_at: '2026-06-27T09:08:00Z',
    action: 'lead.status_changed',
    entity_type: 'safety_lead',
    user_name: 'Dr. R. Moreno',
    ip_address: '127.0.0.1',
  },
  {
    id: 'audit-2',
    created_at: '2026-06-27T09:05:00Z',
    action: 'observation.created',
    entity_type: 'safety_observation',
    user_name: 'system',
    ip_address: '127.0.0.1',
  },
]
